steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-petclinic', '.']

images:
  - 'gcr.io/$PROJECT_ID/spring-petclinic'

options:
  logging: CLOUD_LOGGING_ONLY